# Generated by Django 2.2.12 on 2020-04-20 18:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(blank=True, help_text='Человекопонятный URL-адрес', verbose_name='Слаг')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'db_table': 'news_category_news',
                'verbose_name': 'Название категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TagNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тэг')),
                ('slug', models.SlugField(blank=True, help_text='Человекопонятный URL-адрес', verbose_name='Слаг')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'db_table': 'news_category_tags',
                'verbose_name': 'Название тэга',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='Человекопонятный URL-адрес', verbose_name='Слаг')),
                ('image', models.ImageField(upload_to=news.models.image_folder)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.CategoryNews')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.TagNews')),
            ],
            options={
                'db_table': 'news_category_new',
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
