# Generated by Django 2.2.12 on 2020-04-20 20:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynews',
            name='slug',
            field=models.SlugField(blank=True, help_text='Человекопонятный URL-адрес. Если поле не будет заполнено, то оно сгенерируется автоматически.', verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации'),
        ),
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.CategoryNews', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Вы можете воспользоваться инстументами этого поля для задания форматирования текста', null=True, verbose_name='Содержимое новости'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to=news.models.image_folder, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(blank=True, help_text='Человекопонятный URL-адрес. Если поле не будет заполнено, то оно сгенерируется автоматически.', verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='new',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.TagNews', verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='tagnews',
            name='slug',
            field=models.SlugField(blank=True, help_text='Человекопонятный URL-адрес. Если поле не будет заполнено, то оно сгенерируется автоматически.', verbose_name='Слаг'),
        ),
    ]
