# Generated by Django 2.2.12 on 2020-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200420_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='tag',
        ),
        migrations.AddField(
            model_name='new',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='Тэги', to='news.TagNews', verbose_name='Тэг'),
        ),
    ]
