# Generated by Django 2.2.12 on 2020-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200530_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='Тэги', to='news.TagNews', verbose_name='Тэг'),
        ),
    ]
