# Generated by Django 2.2.12 on 2020-05-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='is_build',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='is_conduct',
            field=models.BooleanField(default=False),
        ),
    ]
