# Generated by Django 2.2.12 on 2020-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200513_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='year',
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='is_build',
            field=models.BooleanField(default=False, help_text='Это поле позволяет отрисовывать турнирную сетку в личном кабинете спортсмена. Необходимо, чтобы перед установкой были корректно сформированы все пары весовых категорий', verbose_name='Пары сформированы'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='is_conduct',
            field=models.BooleanField(default=False, help_text='Необходмо, чтобы перед установкой пары были софрмированы', verbose_name='Турнир проведен'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='name',
            field=models.CharField(help_text='Не забудьте в названии трунира указать год проведение, например: \'Кубок "Львы Белогорья "2019г\'', max_length=80, verbose_name='Название турнира'),
        ),
    ]
