# Generated by Django 2.2.12 on 2020-05-16 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200514_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepair',
            name='delta_rating_sportsman1',
            field=models.SmallIntegerField(default=0, verbose_name='Приращение 1-го'),
        ),
        migrations.AddField(
            model_name='battlepair',
            name='delta_rating_sportsman2',
            field=models.SmallIntegerField(default=0, verbose_name='Приращение 2-го'),
        ),
        migrations.AddField(
            model_name='resultsbattle',
            name='is_not',
            field=models.BooleanField(default=False, help_text='Наличие этого поля присвоит автопоражение спортсмену, но не повлияет на его рейтинг', verbose_name='Болел/Отсутствовал'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='is_conduct',
            field=models.BooleanField(default=False, help_text='Необходмо, чтобы перед установкой пары были сформированы', verbose_name='Турнир проведен'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='name',
            field=models.CharField(help_text='Не забудьте в названии турнира указать год проведения', max_length=80, verbose_name='Название турнира'),
        ),
    ]
