# Generated by Django 2.2.12 on 2020-05-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200516_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsman',
            name='change_rating',
        ),
    ]
