# Generated by Django 2.2.12 on 2020-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_sportsman_change_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlepair',
            name='delta_rating_sportsman1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Приращение 1-го'),
        ),
        migrations.AlterField(
            model_name='battlepair',
            name='delta_rating_sportsman2',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6, verbose_name='Приращение 2-го'),
        ),
        migrations.AlterField(
            model_name='battlepair',
            name='freeze_rating_sportsman1',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Рейтинт 1-го'),
        ),
        migrations.AlterField(
            model_name='battlepair',
            name='freeze_rating_sportsman2',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Рейтинт 2-го'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6, verbose_name='Рейтинг'),
        ),
    ]
