# Generated by Django 2.2.12 on 2020-05-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200516_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlepair',
            name='delta_rating_sportsman1',
            field=models.FloatField(default=0.0, verbose_name='Приращение 1-го'),
        ),
        migrations.AlterField(
            model_name='battlepair',
            name='delta_rating_sportsman2',
            field=models.FloatField(default=0.0, verbose_name='Приращение 2-го'),
        ),
        migrations.AlterField(
            model_name='battlepair',
            name='freeze_rating_sportsman1',
            field=models.FloatField(verbose_name='Рейтинт 1-го'),
        ),
        migrations.AlterField(
            model_name='battlepair',
            name='freeze_rating_sportsman2',
            field=models.FloatField(verbose_name='Рейтинт 2-го'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='rating',
            field=models.FloatField(default=1000.0, verbose_name='Рейтинг'),
        ),
    ]
