# Generated by Django 2.2.12 on 2020-05-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200516_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsSelections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border_x_top_left', models.FloatField(default=-75, help_text='Указывает верхнюю левую границу трапецевидной функции нечёткого множества. Её значение должно быть отрицательным и меньше нижней левой границы этой функции', verbose_name='Верхняя левая граница')),
                ('border_x_bottom_left', models.FloatField(default=-150, help_text='Указывает верхнюю левую границу трапецевидной функции нечёткого множества. Её значение должнго быть отрицательным и больше верхней границы этой функции', verbose_name='Нижняя левая граница')),
                ('border_x_top_right', models.FloatField(default=150, help_text='Указывает верхнюю правую границу трапецевидной функции нечёткого множества. Её значение должно быть положительным и меньше нижней правой границы этой функции', verbose_name='Верхняя правая граница')),
                ('border_x_bottom_right', models.FloatField(default=225, help_text='Указывает верхнюю правую границу трапецевидной функции нечёткого множества. Её значение должнго быть положительным и больше нижней границы этой функции', verbose_name='Нижняя правая граница')),
                ('border_hand_left', models.FloatField(default=50, help_text='Находится в пределах от 0 до 100. Должна быть меньше правой границы', verbose_name='Левая граница')),
                ('border_hand_right', models.FloatField(default=70, help_text='Находится в пределах от 0 до 100. Должна быть больше левой границы', verbose_name='Правая граница')),
                ('border_foot_left', models.FloatField(default=30, help_text='Находится в пределах от 0 до 100. Должна быть меньше правой границы', verbose_name='Левая граница')),
                ('border_foot_right', models.FloatField(default=50, help_text='Находится в пределах от 0 до 100. Должна быть больше левой границы', verbose_name='Правая граница')),
                ('mu', models.FloatField(default=0.5, help_text='Находится в пределах от 0 до 1', verbose_name='Граница степени принадлежности')),
                ('active', models.BooleanField(blank=True, verbose_name='Активировать настройку')),
            ],
            options={
                'verbose_name': 'Настройка подбора соперника',
                'db_table': 'account_settings_selection',
                'verbose_name_plural': 'Настройки подбора соперников',
            },
        ),
    ]
