# Generated by Django 2.2.12 on 2020-05-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_settingsselections'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsselections',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='settingsselections',
            name='active',
            field=models.BooleanField(blank=True, verbose_name='Активировать'),
        ),
        migrations.AlterField(
            model_name='settingsselections',
            name='mu',
            field=models.FloatField(default=0.5, help_text='Находится в пределах от 0 до 1', verbose_name='μ'),
        ),
    ]
