# Generated by Django 2.2.12 on 2020-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200528_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsselections',
            name='active',
            field=models.BooleanField(blank=True, verbose_name='Активная'),
        ),
    ]
